=head1 NAME

Finance::Quote::YahooJapan - A Perl module that enables GnuCash to get quotes of Japanese stocks and funds from Yahoo! JAPAN.

=head1 DESCRIPTION

Finance::Quote::YahooJapan is a submodule of Finance::Quote, and adds support for Japanese stock and mutual fund quotes.
This module allows GnuCash to fetch these quotes from Yahoo! Finance JAPAN L<http://finance.yahoo.co.jp/> with online price update feature.

This module obtains quotes by extracting them from the search result pages of Yahoo! Finance JAPAN's stock price search service. Thus the information obtained by this module is covered by Yahoo's terms and conditions. See L<http://finance.yahoo.co.jp/> for more details.

See my blog article for more detailed information: L<http://liosk.blog103.fc2.com/blog-entry-185.html> (ja)

=head1 USAGE

=head2 1. Install Finance::Quote

Install and setup Finance::Quote module as explained in the GnuCash Help Manual: L<http://svn.gnucash.org/docs/C/gnucash-help/acct-create.html#Online-price-setup>

=head2 2. Install Finance::Quote::YahooJapan

a. Locate the directory where Finance::Quote is installed and then put the submodule file F<YahooJapan.pm> at F<Finance/Quote/YahooJapan.pm>.

b. Set the C<FQ_LOAD_QUOTELET> environment variable to C<-defaults YahooJapan> so that Finance::Quote will load Finance::Quote::YahooJapan.

=head2 3. Setup GnuCash Online Quote Feature

Launch GnuCash and setup your securities as explained in the Manual: L<http://svn.gnucash.org/docs/C/gnucash-help/acct-create.html#Online-price-setup>

=head1 LIMITATIONS

Finance::Quote::YahooJapan fails to fetch quotes of some securities under certain conditions, because this module extracts quotes from only a limited number of paginated search result pages though Yahoo! Finance JAPAN's stock price search service returns a lot of unrelated securities that partially match to a search query. Yahoo tends to return too many unrelated securities when a search query contains a simple symbol (such as C<1> and C<T>) that does not look like an actual Japanese ticker symbol. If you cannot get a quote of a target security, please examine your search query and remove such simple symbols (if any). Also, appending market selector letters to stock codes, like making C<1305> into C<1305.t>, will be helpful in some cases.

=cut
